better bash

diff --git a/gitbot/config b/gitbot/config
--- a/gitbot/config
+++ b/gitbot/config
@@ -1,7 +1,12 @@
 #!/usr/bin/env bash
 
-GIT_USER_NAME="Paolo Brasolin (Travis CI)"
-GIT_USER_EMAIL="paolo.brasolin@gmail.com"
-GIT_SOURCE_BRANCH=source
-GIT_TARGET_BRANCH=target
-GIT_TARGET_FOLDER=output
+# Exit with nonzero exit code if anything fails.
+set -e
+
+export GITBOT_USER_NAME="Paolo Brasolin (Travis CI)"
+export GITBOT_USER_EMAIL="paolo.brasolin@gmail.com"
+export GITBOT_SOURCE_BRANCH=source
+export GITBOT_TARGET_BRANCH=target
+export GITBOT_TARGET_FOLDER=output
+export GITBOT_ROOT=$TRAVIS_BUILD_DIR/gitbot
+
